#!/bin/bash

echo "🎮 Online Multiplayer Test Scripti"
echo "=================================="
echo ""
echo "Bu script ile online testi yapabilirsiniz:"
echo ""
echo "1. Backend'i başlatın:"
echo "   cd backend-dotnet/src/API && dotnet run"
echo ""
echo "2. Ngrok ile backend'i internete açın:"
echo "   ngrok http 5227"
echo ""
echo "3. Ngrok'un verdiği HTTPS URL'i kopyalayın (örn: https://abc123.ngrok.io)"
echo ""
echo "4. src/config/env.ts dosyasında API_URL'i değiştirin:"
echo "   export const API_URL = 'https://abc123.ngrok.io';"
echo ""
echo "5. Uygulamayı başlatın:"
echo "   npx expo start"
echo ""
echo "6. İki farklı cihazdan QR kod ile bağlanın ve test edin"
echo ""
echo "=================================="
echo ""
echo "Test Senaryoları:"
echo "- Kullanıcı 1: Kayıt ol ve match ara"
echo "- Kullanıcı 2: Kayıt ol ve match ara"
echo "- İki kullanıcı eşleştiğinde oyunu oyna"
echo "- Network bağlantısını kes/aç (bağlantı kopması testi)"
echo "- Süre dolması testi (30 saniye bekle)"
echo ""

